// user reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_ALLUSER = "SET_ALLUSER";
export const SET_PAYEMENT_CARD = "SET_PAYEMENT_CARD";

// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const BUTTON_LOADING = "BUTTON_LOADING";
export const LOADING_CLEAR = "LOADING_CLEAR";

// Business reducer types
export const SET_BUSINESS_DETAILS = "SET_BUSINESS_DETAILS";

// Client reducer types
export const SET_CLIENTS = "SET_CLIENTS";
export const SET_CLIENT = "SET_CLIENT";

//Products reducer types
export const SET_PRODUCT_CATEGORIES = "SET_PRODUCT_CATEGORIES";
export const SET_PRODUCT_CATEGORY = "SET_PRODUCT_CATEGORY";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_VIEW = "SET_PRODUCT_VIEW";
export const SET_PRODUCT_CATEGORIES_DATA = "SET_PRODUCT_CATEGORIES_DATA";
export const SET_PRODUCT_ORDER_DATA = "SET_PRODUCT_ORDER_DATA";
export const SET_PRODUCT_SETTINGS_DATA = "SET_PRODUCT_SETTINGS_DATA";

// Service reducer types
export const SET_SERVICE_CATEGORIES = "SET_SERVICE_CATEGORIES";
export const SET_SERVICE_CATEGORY = "SET_SERVICE_CATEGORY";
export const SET_SERVICES = "SET_SERVICES";
export const SET_SERVICE_ORDERS = "SET_SERVICE_ORDERS";
export const SET_ROOT_SERVICE_CATEGORIES = "SET_ROOT_SERVICE_CATEGORIES";
export const SET_SERVICE_DATA = "SET_SERVICE_DATA";
export const SET_SERVICE_SERVICE_DATA = "SET_SERVICE_SERVICE_DATA";
export const SET_STAFF_SERVICE = "SET_STAFF_SERVICE";

// Report reducer types
export const SET_THIRTY_DAY_SNAPSHOT = "SET_THIRTY_DAY_SNAPSHOT";
export const SET_TOTAL_SALES = "SET_TOTAL_SALES";
export const SET_REPORT_TOTAL_SALES = "SET_REPORT_TOTAL_SALES";
export const SET_REPORT_ESTIMATED_PAYROLL = "SET_REPORT_ESTIMATED_PAYROLL";
export const SET_REPORT_SERVICES_COMPLETED = "SET_REPORT_SERVICES_COMPLETED";
export const SET_REPORT_PRODUCT_SALES = "SET_REPORT_PRODUCT_SALES";
export const SET_REPORT_CLIENT_REPORT = "SET_REPORT_CLIENT_REPORT";
export const SET_REPORT_CLIENT_REBOOKINGS = "SET_REPORT_CLIENT_REBOOKINGS";
export const SET_STAFF_BOOKING_ANALYSIS = "SET_STAFF_BOOKING_ANALYSIS";
export const SET_PRODUCT_ORDER = "SET_PRODUCT_ORDER";
export const SET_SERVICE_ORDER = "SET_SERVICE_ORDER";
export const SET_DASHBOARD_CHART = "SET_DASHBOARD_CHART";


// Staff reducer types
export const SET_STAFFS = "SET_STAFFS";
export const SET_STAFF = "SET_STAFF";
export const SET_STYLIST = "SET_STYLIST";
export const SET_STAFF_RESOURCES = "SET_STAFF_RESOURCES";
export const SET_STAFF_RESPONSE_DATA = "SET_STAFF_RESPONSE_DATA";

// Schedule reducer types
export const TIME_SLOTS = "TIME_SLOTS";
export const SCHEDUELES = "SCHEDUELES";
export const SET_APPOITNMENT = "SET_APPOITNMENT";
export const SET_APPOITNMENT_ORDER = "SET_APPOITNMENT_ORDER";

//Message reducer types
export const SET_URL = "SET_URL";